name: Benchmark main.py

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      base-branch:
        description: 'Base branch to compare against (default: main)'
        required: false
        default: 'main'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (optional)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run benchmark comparison
        run: |
          BASE="${{ github.event.inputs.base-branch || 'main' }}"
          python bench_compare.py "$BASE" > bench_results.txt

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: bench_results.txt
