name: Benchmark main.py

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      base-branch:
        description: 'Base branch to compare against (default: main)'
        required: false
        default: 'main'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - id: benchmark
        name: Run benchmark comparison
        run: |
          BASE="${{ github.event.inputs.base-branch || 'main' }}"
          python bench_compare.py "$BASE" | tee bench_results.txt
          echo "results<<EOF" >> $GITHUB_OUTPUT
          cat bench_results.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: bench_results.txt

      - name: Comment results on PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🔬 Benchmark Results
            ```
            ${{ steps.benchmark.outputs.results }}
            ```
