name: Run Optimizer

on:
  issue_comment:
    types: [created]

jobs:
  optimizer:
    # run only when the comment is on a PR and contains "/optimize"
    if: ${{ github.event.issue.pull_request != null && contains(github.event.comment.body, '/optimize') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (optional)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run optimizer
        run: python optimizer.py > optimizer_results.txt

      - name: Upload optimizer results
        uses: actions/upload-artifact@v4
        with:
          name: optimizer-results
          path: optimizer_results.txt
