name: Run Optimizer

on:
  issue_comment:
    types: [created]

jobs:
  optimizer:
    if: github.event.issue.pull_request != null && github.event.comment.body == '/optimize'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run optimizer
        run: python optimizer.py > optimizer_results.txt

      - uses: actions/upload-artifact@v4
        with:
          name: optimizer-results
          path: optimizer_results.txt
